- name: Install Screenly OSE Monitoring
  hosts: all
  user: pi
  become: yes
  vars:
    monitor_branch: "{{ lookup('env', 'MONITOR_BRANCH') }}"

  handlers:
    - name: restart-nginx
      service:
        name: nginx
        state: restarted

  roles:
    - monitoring
