# Check older versions
- stat:
    path: /etc/nginx/sites-enabled/monitor.conf
  register: monitorScript_s
  
- stat:
    path: /var/www/html/assets/tools/version.txt
  register: version1_0_s
  
- set_fact: version1_0="{{version1_0_s.stat.exists}}"
  
- stat:
    path: /var/www/html/monitor/assets/tools/version.txt
  register: version1_1_s

- set_fact: version1_1="{{version1_1_s.stat.exists}}"

- name: check for existing ose-monitoring install
  stat:
    path: "/usr/bin/ose-monitoring"
  register: monitorScript_s
  when: not version1_0 and not version1_1

- set_fact: monitorScript="{{monitorScript_s.stat.exists}}"

- name: check ose-monitoring version
  command: "/usr/bin/ose-monitoring --version"
  register: monitor_script_version
  when: monitorScript and not version1_0 and not version1_1
  changed_when: False
  failed_when: False

- set_fact: update_version="True"
  when: (version1_0) or (version1_1) or (monitor_script_version <= "1.4")

- name: Backup Database
  copy:
    src: /var/www/html/dbase.db
    dest: /home/pi/.monitor/dbase.db.bak
    owner: root
    group: root
  when: update_version
  
- name: Backup Database
  copy:
    src: /var/www/html/monitor/dbase.db
    dest: /home/pi/.monitor/dbase.db.bak
    owner: root
    group: root
  when: update_version
  
# Update ose-monitoring
- name: Install packages
  apt:
    install: "{{ item }}"
    state: latest
  with_items:
    - nginx-light
    - php-fpm 
    - php7.0-sqlite 
    - php7.0-curl

- name: Copy ose-monitoring
  copy:
    src: /tmp/monitor
    dest: /var/www/html/monitor
    owner: www-data
    group: www-data
    mode: 0644
    
- name: Copy monitoring.conf
  copy:
    src: monitoring.conf
    dest: /etc/nginx/sites-enabled/monitoring.conf
    owner: root 
    group: root
    mode: 0644
  notify:
    - restart-nginx
    
- name: Copy ose-monitoring Script
  copy:
    src: ose-monitoring
    dest: /usr/bin/ose-monitoring
    owner: root 
    group: root
    mode: 0644

- file:
    path: /home/pi/.monitor
    state: directory
    owner: pi
    group: pi
    mode: 0644

- file:
    path: /var/www/html/monitor
    state: directory
    owner: www-data
    group: www-data
    recurse: yes

- name: Retore Database Backup
  copy:
    src: /home/pi/.monitor/dbase.db.bak
    dest: /var/www/html/monitor/dbase.db
    owner: www-data
    group: www-data
    mode: 0644
  when: update_version
    
- name: Version update
  command: ose-monitoring --init