# Check older versions
- name: check if older version installed
  stat:
    path: /etc/nginx/sites-enabled/monitor.conf
  register: monitorScript_s

- set_fact: old_monitor="{{monitorScript_s.stat.exists}}"
  
- name: check if version 1.0 installed
  stat:
    path: /var/www/html/assets/tools/version.txt
  register: version1_0_s
  
- set_fact: version1_0="{{version1_0_s.stat.exists}}"

- name: check if version 1.1 installed  
  stat:
    path: /var/www/html/monitor/assets/tools/version.txt
  register: version1_1_s

- set_fact: version1_1="{{version1_1_s.stat.exists}}"

- name: check if version >1.1 installed
  stat:
    path: "/usr/bin/ose-monitoring"
  register: version_newer_s

- set_fact: version_newer="{{version_newer_s.stat.exists}}"

- set_fact: update_version="True"
  when: (old_monitor) and (version1_0 or version1_1 or version_newer)

- name: Backup Database
  copy:
    src: /var/www/html/dbase.db
    dest: /home/pi/.monitor/dbase.db.bak
    owner: root
    group: root
  when: update_version and version1_0
  
- name: Backup Database
  copy:
    src: /var/www/html/monitor/dbase.db
    dest: /home/pi/.monitor/dbase.db.bak
    owner: root
    group: root
  when: update_version and (version1_1 or version_newer)
  
# Update ose-monitoring
- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - nginx-light
    - php-fpm 
    - php7.0-sqlite 
    - php7.0-curl

- name: Copy ose-monitoring
  copy:
    src: /tmp/monitor
    dest: /var/www/html/monitor
    owner: www-data
    group: www-data
    mode: 0644
    
- name: Copy monitoring.conf
  copy:
    src: monitoring.conf
    dest: /etc/nginx/sites-enabled/monitoring.conf
    owner: root 
    group: root
    mode: 0644
  notify:
    - restart-nginx
    
- name: Copy ose-monitoring Script
  copy:
    src: ose-monitoring
    dest: /usr/bin/ose-monitoring
    owner: root 
    group: root
    mode: 0644

- file:
    path: /home/pi/.monitor
    state: directory
    owner: pi
    group: pi
    mode: 0644

- file:
    path: /var/www/html/monitor
    state: directory
    owner: www-data
    group: www-data
    recurse: yes

- name: Retore Database Backup
  copy:
    src: /home/pi/.monitor/dbase.db.bak
    dest: /var/www/html/monitor/dbase.db
    owner: www-data
    group: www-data
    mode: 0644
  when: update_version and not version_newer
    
- name: Version update
  command: ose-monitoring --init