name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
 main:
   runs-on: ubuntu-latest
   steps:
     -
       name: Setup Docker Buildx
       uses: docker/setup-buildx-action@v1
     -
       name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}
     -
       name: Set up QEMU
       uses: docker/setup-qemu-action@v1
     -
       name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         push: true
         platforms: linux/amd64,linux/arm/v7,linux/arm64
         tags:  ${{ secrets.DOCKER_USERNAME }}/somo:latest
         cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/somo:latest
         cache-to: type=inline
